export interface DemoCamperItem {
  id: string;
  slug: string;
  title: string;
  brand: string;
  model: string;
  vehicleType: string;
  year: number;
  island: string;
  municipality: string;
  addressApprox: string;
  latitude: number;
  longitude: number;
  passengers: number;
  beds: number;
  doors: number;
  transmission: string;
  fuelType: string;
  fuelConsumption: string;
  basePricePerDay: number;
  includedKmPerDay: number;
  extraKmPrice: number;
  securityDeposit: number;
  cleaningFee: number;
  minDays: number;
  maxDays: number;
  bookingType: string;
  cancellationPolicy: string;
  description: string;
  rules: string;
  status: 'ACTIVE';
  isVip?: boolean;
  isFeatured?: boolean;
  isDemoVehicle: true;
  owner: {
    id: string;
    firstName: string;
    lastName: string;
    avatarUrl: string;
    verification: string;
    phone: string;
    email: string;
  };
  photos: { id: string; url: string; orderIndex: number }[];
  features: { id: string; name: string }[];
  reviews: { id: string; rating: number; comment: string; author: { firstName: string; avatarUrl?: string } }[];
}

export const REALISTIC_CANARIAN_CAMPERS: DemoCamperItem[] = [
  {
    id: 'demo-gc-1',
    slug: 'volkswagen-california-ocean-t6-1-dsg-gran-canaria',
    title: 'Volkswagen California Ocean T6.1 DSG Automática',
    brand: 'Volkswagen',
    model: 'California Ocean T6.1',
    vehicleType: 'TURISMO_CAMPERIZADO',
    year: 2023,
    island: 'Gran Canaria',
    municipality: 'Las Palmas de Gran Canaria',
    addressApprox: 'Paseo de Las Canteras / Guanarteme',
    latitude: 28.1340,
    longitude: -15.4410,
    passengers: 4,
    beds: 4,
    doors: 4,
    transmission: 'AUTOMATIC',
    fuelType: 'DIESEL',
    fuelConsumption: '7.2 L/100km',
    basePricePerDay: 85,
    includedKmPerDay: 150,
    extraKmPrice: 0.25,
    securityDeposit: 600,
    cleaningFee: 35,
    minDays: 2,
    maxDays: 30,
    bookingType: 'REQUEST_TO_BOOK',
    cancellationPolicy: 'MODERATE',
    status: 'ACTIVE',
    isDemoVehicle: true,
    isFeatured: true,
    description: 'Nuestra California Ocean está como nueva, equipada con techo elevable electrohidráulico, calefacción estática digital, cocina completa de 2 fuegos, nevera compresor de 42L, ducha exterior y toldo lateral Fiamma. Muy cómoda de conducir en las curvas de la cumbre y perfecta para pernoctar en Agaete o Tamadaba.',
    rules: 'No fumar en el interior. Mascotas consultar previamente. Devolver con el depósito de combustible y aguas limpias al mismo nivel que en la entrega.',
    owner: {
      id: 'owner-demo-1',
      firstName: 'Yeray',
      lastName: 'Marrero',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
      verification: 'VERIFIED',
      phone: '+34 628 412 901',
      email: 'yeray.marrero@canarias-campers.local',
    },
    photos: [
      { id: 'p1-1', url: 'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?w=1200', orderIndex: 0 },
      { id: 'p1-2', url: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1200', orderIndex: 1 },
      { id: 'p1-3', url: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=1200', orderIndex: 2 },
      { id: 'p1-4', url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200', orderIndex: 3 },
    ],
    features: [
      { id: 'f1-1', name: 'Techo elevable electrohidráulico' },
      { id: 'f1-2', name: 'Calefacción estacionaria' },
      { id: 'f1-3', name: 'Cocina de gas 2 fuegos' },
      { id: 'f1-4', name: 'Nevera compresor 42L' },
      { id: 'f1-5', name: 'Ducha exterior' },
      { id: 'f1-6', name: 'Toldo lateral Fiamma' },
      { id: 'f1-7', name: 'Mesa y sillas camping' },
      { id: 'f1-8', name: 'Placa solar 150W' },
    ],
    reviews: [
      { id: 'r1-1', rating: 5, comment: 'Increíble furgoneta, impecable por dentro y Yeray nos dio las mejores recomendaciones de Gran Canaria.', author: { firstName: 'Mateo', avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200' } },
      { id: 'r1-2', rating: 5, comment: 'The California Ocean was super smooth to drive and very well equipped. 100% recommended!', author: { firstName: 'Sophie', avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200' } },
    ],
  },
  {
    id: 'demo-tf-2',
    slug: 'fiat-ducato-maxi-gran-volumen-l3h2-tenerife',
    title: 'Fiat Ducato Maxi Gran Volumen L3H2 con Baño y Ducha Caliente',
    brand: 'Fiat',
    model: 'Ducato Maxi L3H2',
    vehicleType: 'CAMPER_GRAN_VOLUMEN',
    year: 2022,
    island: 'Tenerife',
    municipality: 'Santa Cruz de Tenerife',
    addressApprox: 'Cerca de Dársena Pesquera / San Andrés',
    latitude: 28.4980,
    longitude: -16.2050,
    passengers: 3,
    beds: 3,
    doors: 4,
    transmission: 'MANUAL',
    fuelType: 'DIESEL',
    fuelConsumption: '8.8 L/100km',
    basePricePerDay: 98,
    includedKmPerDay: 200,
    extraKmPrice: 0.22,
    securityDeposit: 750,
    cleaningFee: 40,
    minDays: 2,
    maxDays: 30,
    bookingType: 'REQUEST_TO_BOOK',
    cancellationPolicy: 'MODERATE',
    status: 'ACTIVE',
    isDemoVehicle: true,
    isFeatured: true,
    description: 'Camper gran volumen con aislamiento térmico Kaiflex de alta densidad. Dispone de cama doble fija trasera viscoelástica, salón convertible, baño completo con ducha de agua caliente a gas Truma, WC químico giratorio Dometic, placa solar de 300W e inversor de 2000W para cargar portátiles y cámaras.',
    rules: 'Prohibido encender velas dentro. Prohibido fumar. Respetar las zonas de pernocta autorizadas del Parque Nacional del Teide.',
    owner: {
      id: 'owner-demo-2',
      firstName: 'Guacimara',
      lastName: 'Rodríguez',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
      verification: 'VERIFIED',
      phone: '+34 622 890 145',
      email: 'guacimara.rodriguez@canarias-campers.local',
    },
    photos: [
      { id: 'p2-1', url: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=1200', orderIndex: 0 },
      { id: 'p2-2', url: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=1200', orderIndex: 1 },
      { id: 'p2-3', url: 'https://images.unsplash.com/photo-1506015391300-4802dc74de2e?w=1200', orderIndex: 2 },
    ],
    features: [
      { id: 'f2-1', name: 'Ducha interior con agua caliente' },
      { id: 'f2-2', name: 'WC Químico Dometic' },
      { id: 'f2-3', name: 'Cama viscoelástica fija' },
      { id: 'f2-4', name: 'Placa solar 300W' },
      { id: 'f2-5', name: 'Inversor 220V 2000W' },
      { id: 'f2-6', name: 'Agua caliente Truma' },
      { id: 'f2-7', name: 'Calefacción estacionaria' },
    ],
    reviews: [
      { id: 'r2-1', rating: 5, comment: 'La ducha con agua caliente en medio del Teide es un auténtico lujo. La furgoneta es un apartamento rodante.', author: { firstName: 'Javier', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200' } },
      { id: 'r2-2', rating: 5, comment: 'Guacimara fue súper atenta y la camper estaba impecable.', author: { firstName: 'Elena', avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200' } },
    ],
  },
  {
    id: 'demo-gc-3',
    slug: 'mercedes-benz-marco-polo-4matic-traccion-total-gran-canaria',
    title: 'Mercedes-Benz Marco Polo 4Matic Tracción Total',
    brand: 'Mercedes-Benz',
    model: 'Marco Polo Clase V 4Matic',
    vehicleType: 'TURISMO_CAMPERIZADO',
    year: 2023,
    island: 'Gran Canaria',
    municipality: 'Telde',
    addressApprox: 'Entrega directa en Aeropuerto de Gran Canaria (LPA)',
    latitude: 27.9319,
    longitude: -15.3866,
    passengers: 4,
    beds: 4,
    doors: 4,
    transmission: 'AUTOMATIC',
    fuelType: 'DIESEL',
    fuelConsumption: '7.5 L/100km',
    basePricePerDay: 110,
    includedKmPerDay: 150,
    extraKmPrice: 0.30,
    securityDeposit: 800,
    cleaningFee: 40,
    minDays: 2,
    maxDays: 30,
    bookingType: 'REQUEST_TO_BOOK',
    cancellationPolicy: 'MODERATE',
    status: 'ACTIVE',
    isDemoVehicle: true,
    isFeatured: true,
    description: 'La elegancia y confort de Mercedes-Benz con la tracción integral 4Matic para subir a los puntos más altos de Gran Canaria sin esfuerzo. Acabados en madera de barco, suelo estilo yate, doble cama matrimonio y climatización bizona.',
    rules: 'Entrega en el Aeropuerto de Gran Canaria sin coste adicional. Devolver limpia y repostada.',
    owner: {
      id: 'owner-demo-3',
      firstName: 'Nauzet',
      lastName: 'Santana',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
      verification: 'VERIFIED',
      phone: '+34 633 112 233',
      email: 'nauzet.santana@canarias-campers.local',
    },
    photos: [
      { id: 'p3-1', url: 'https://images.unsplash.com/photo-1513311068348-19c8fbdc0bb6?w=1200', orderIndex: 0 },
      { id: 'p3-2', url: 'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?w=1200', orderIndex: 1 },
      { id: 'p3-3', url: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1200', orderIndex: 2 },
    ],
    features: [
      { id: 'f3-1', name: 'Tracción 4Matic 4x4' },
      { id: 'f3-2', name: 'Techo elevable eléctrico' },
      { id: 'f3-3', name: 'Cocina de diseño' },
      { id: 'f3-4', name: 'Doble batería AGM' },
      { id: 'f3-5', name: 'Control de crucero adaptativo' },
    ],
    reviews: [
      { id: 'r3-1', rating: 5, comment: 'La mejor camper que he conducido. Muy silenciosa y comodísima.', author: { firstName: 'Álvaro', avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200' } },
    ],
  },
  {
    id: 'demo-gc-4',
    slug: 'toyota-hilux-4x4-expedition-tienda-techo-gran-canaria',
    title: 'Toyota Hilux 4x4 Expedition con Tienda de Techo Rígida',
    brand: 'Toyota',
    model: 'Hilux Invincible 4x4 Overland',
    vehicleType: '4X4_CAMPERIZADO',
    year: 2022,
    island: 'Gran Canaria',
    municipality: 'San Bartolomé de Tirajana',
    addressApprox: 'Maspalomas / El Tablero',
    latitude: 27.7606,
    longitude: -15.5860,
    passengers: 2,
    beds: 2,
    doors: 4,
    transmission: 'MANUAL',
    fuelType: 'DIESEL',
    fuelConsumption: '8.4 L/100km',
    basePricePerDay: 90,
    includedKmPerDay: 200,
    extraKmPrice: 0.25,
    securityDeposit: 700,
    cleaningFee: 30,
    minDays: 2,
    maxDays: 30,
    bookingType: 'REQUEST_TO_BOOK',
    cancellationPolicy: 'MODERATE',
    status: 'ACTIVE',
    isDemoVehicle: true,
    description: 'Para los verdaderos amantes de la aventura y el off-road controlado. Toyota Hilux con tienda de techo James Baroud de apertura hidráulica en 10 segundos, módulo cocina extraíble de maletero, depósito de agua de 60L con ducha y compresor de aire ARB.',
    rules: 'Solo circular por pistas y carreteras autorizadas. Respetar siempre el medioambiente y parques naturales.',
    owner: {
      id: 'owner-demo-4',
      firstName: 'Ayoze',
      lastName: 'Betancor',
      avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400',
      verification: 'VERIFIED',
      phone: '+34 611 776 544',
      email: 'ayoze.betancor@canarias-campers.local',
    },
    photos: [
      { id: 'p4-1', url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200', orderIndex: 0 },
      { id: 'p4-2', url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200', orderIndex: 1 },
      { id: 'p4-3', url: 'https://images.unsplash.com/photo-1506015391300-4802dc74de2e?w=1200', orderIndex: 2 },
    ],
    features: [
      { id: 'f4-1', name: 'Tracción 4x4 con reductora' },
      { id: 'f4-2', name: 'Tienda de techo rígida James Baroud' },
      { id: 'f4-3', name: 'Módulo de cocina en maletero' },
      { id: 'f4-4', name: 'Ducha exterior 60L' },
      { id: 'f4-5', name: 'Nevera de compresor 35L' },
    ],
    reviews: [
      { id: 'r4-1', rating: 5, comment: 'Dormir sobre el techo en lo alto de Gran Canaria con el cielo estrellado fue una experiencia brutal.', author: { firstName: 'David', avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200' } },
    ],
  },
  {
    id: 'demo-tf-5',
    slug: 'citroen-jumper-nomad-living-l2h2-tenerife',
    title: 'Citroën Jumper Nomad Living L2H2 Camperizada con Madera',
    brand: 'Citroën',
    model: 'Jumper Nomad Living',
    vehicleType: 'CAMPER_GRAN_VOLUMEN',
    year: 2021,
    island: 'Tenerife',
    municipality: 'San Cristóbal de La Laguna',
    addressApprox: 'Cerca del Aeropuerto Tenerife Norte (TFN)',
    latitude: 28.4874,
    longitude: -16.3159,
    passengers: 2,
    beds: 2,
    doors: 4,
    transmission: 'MANUAL',
    fuelType: 'DIESEL',
    fuelConsumption: '8.2 L/100km',
    basePricePerDay: 78,
    includedKmPerDay: 150,
    extraKmPrice: 0.20,
    securityDeposit: 500,
    cleaningFee: 30,
    minDays: 2,
    maxDays: 30,
    bookingType: 'REQUEST_TO_BOOK',
    cancellationPolicy: 'MODERATE',
    status: 'ACTIVE',
    isDemoVehicle: true,
    description: 'Camperización artesanal en madera de pino canario y estilo rústico acogedor. Cama fija super cómoda de 135x190cm, claraboya panorámica para ver las estrellas, proyector de cine portátil incluido y batería de litio que nunca te deja sin luz.',
    rules: 'Cuidar la madera como si fuera tu casa. No utilizar zapatos de calle en la zona de tarima interior.',
    owner: {
      id: 'owner-demo-5',
      firstName: 'Idaira',
      lastName: 'Ramos',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
      verification: 'VERIFIED',
      phone: '+34 644 321 987',
      email: 'idaira.ramos@canarias-campers.local',
    },
    photos: [
      { id: 'p5-1', url: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=1200', orderIndex: 0 },
      { id: 'p5-2', url: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=1200', orderIndex: 1 },
    ],
    features: [
      { id: 'f5-1', name: 'Cama matrimonio 135x190' },
      { id: 'f5-2', name: 'Claraboya panorámica' },
      { id: 'f5-3', name: 'Batería de Litio LiFePO4' },
      { id: 'f5-4', name: 'Cocina 2 fuegos' },
    ],
    reviews: [
      { id: 'r5-1', rating: 5, comment: 'La furgo más bonita que hemos visto. Súper romántica y cómoda para recorrer Tenerife.', author: { firstName: 'Carla', avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200' } },
    ],
  },
  {
    id: 'demo-tf-6',
    slug: 'autocaravana-benimar-sport-346-6-plazas-tenerife',
    title: 'Autocaravana Benimar Sport 346 Familiar 6 Plazas',
    brand: 'Benimar',
    model: 'Sport 346 Capuchina',
    vehicleType: 'AUTOCARAVANA',
    year: 2022,
    island: 'Tenerife',
    municipality: 'Adeje',
    addressApprox: 'Costa Adeje / Playa Paraíso',
    latitude: 28.1200,
    longitude: -16.7300,
    passengers: 6,
    beds: 6,
    doors: 3,
    transmission: 'MANUAL',
    fuelType: 'DIESEL',
    fuelConsumption: '10.5 L/100km',
    basePricePerDay: 135,
    includedKmPerDay: 180,
    extraKmPrice: 0.25,
    securityDeposit: 900,
    cleaningFee: 50,
    minDays: 2,
    maxDays: 30,
    bookingType: 'REQUEST_TO_BOOK',
    cancellationPolicy: 'MODERATE',
    status: 'ACTIVE',
    isDemoVehicle: true,
    description: 'La opción reina para familias numerosas o grupos de amigos. Cuenta con doble comedor, 6 plazas homologadas para viajar y dormir, garaje gigante para tablas de surf o bicicletas, gran frigorífico automático de 140L y baño completo con cabina de ducha separada.',
    rules: 'Obligatorio carné B con al menos 2 años de antigüedad. No se permite fumar en el interior.',
    owner: {
      id: 'owner-demo-6',
      firstName: 'Rayco',
      lastName: 'Cabrera',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400',
      verification: 'VERIFIED',
      phone: '+34 655 889 900',
      email: 'rayco.cabrera@canarias-campers.local',
    },
    photos: [
      { id: 'p6-1', url: 'https://images.unsplash.com/photo-1513311068348-19c8fbdc0bb6?w=1200', orderIndex: 0 },
      { id: 'p6-2', url: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=1200', orderIndex: 1 },
    ],
    features: [
      { id: 'f6-1', name: '6 plazas viajar y dormir' },
      { id: 'f6-2', name: 'Garaje XXL' },
      { id: 'f6-3', name: 'Frigorífico 140L' },
      { id: 'f6-4', name: 'Cabina de ducha separada' },
      { id: 'f6-5', name: 'Portabicicletas para 4' },
    ],
    reviews: [
      { id: 'r6-1', rating: 5, comment: 'Viajamos con nuestros 3 hijos y estuvimos de maravilla. Espaciosa y muy fácil de manejar.', author: { firstName: 'Familia Gómez', avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200' } },
    ],
  },
  {
    id: 'demo-fv-7',
    slug: 'ford-transit-custom-nugget-plus-fuerteventura',
    title: 'Ford Transit Custom Nugget Plus Techo Alto Fijo',
    brand: 'Ford',
    model: 'Transit Custom Nugget Plus Westfalia',
    vehicleType: 'CAMPER_GRAN_VOLUMEN',
    year: 2023,
    island: 'Fuerteventura',
    municipality: 'La Oliva',
    addressApprox: 'Corralejo / Dunas de Fuerteventura',
    latitude: 28.7300,
    longitude: -13.8700,
    passengers: 4,
    beds: 4,
    doors: 4,
    transmission: 'MANUAL',
    fuelType: 'DIESEL',
    fuelConsumption: '7.8 L/100km',
    basePricePerDay: 82,
    includedKmPerDay: 150,
    extraKmPrice: 0.20,
    securityDeposit: 600,
    cleaningFee: 35,
    minDays: 2,
    maxDays: 30,
    bookingType: 'REQUEST_TO_BOOK',
    cancellationPolicy: 'MODERATE',
    status: 'ACTIVE',
    isDemoVehicle: true,
    description: 'La distribución Westfalia de doble espacio con cocina en la parte trasera y WC integrado. Techo alto rígido que permite estar de pie en todo momento sin ruidos de viento. Ideal para los vientos alisios de Fuerteventura y amantes del surf y kite en El Cotillo.',
    rules: 'No transitar por pistas de arena suelta no compactada. Prohibido fumar.',
    owner: {
      id: 'owner-demo-7',
      firstName: 'Yaiza',
      lastName: 'Hernández',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400',
      verification: 'VERIFIED',
      phone: '+34 612 345 678',
      email: 'yaiza.hernandez@canarias-campers.local',
    },
    photos: [
      { id: 'p7-1', url: 'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?w=1200', orderIndex: 0 },
      { id: 'p7-2', url: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=1200', orderIndex: 1 },
    ],
    features: [
      { id: 'f7-1', name: 'Techo alto rígido' },
      { id: 'f7-2', name: 'WC químico integrado' },
      { id: 'f7-3', name: 'Cocina en L trasera' },
      { id: 'f7-4', name: 'Nevera 40L' },
      { id: 'f7-5', name: 'Baca porta-surf' },
    ],
    reviews: [
      { id: 'r7-1', rating: 5, comment: 'Perfect camper for our surf trip in Fuerteventura! Clean, reliable and Yaiza is super friendly.', author: { firstName: 'Lucas', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200' } },
    ],
  },
  {
    id: 'demo-lz-8',
    slug: 'renault-trafic-horizon-edition-famara-lanzarote',
    title: 'Renault Trafic Horizon Edition Especial Famara',
    brand: 'Renault',
    model: 'Trafic Horizon Edition',
    vehicleType: 'TURISMO_CAMPERIZADO',
    year: 2022,
    island: 'Lanzarote',
    municipality: 'Teguise',
    addressApprox: 'Caleta de Famara / La Villa de Teguise',
    latitude: 29.1120,
    longitude: -13.5650,
    passengers: 3,
    beds: 2,
    doors: 4,
    transmission: 'MANUAL',
    fuelType: 'DIESEL',
    fuelConsumption: '6.9 L/100km',
    basePricePerDay: 68,
    includedKmPerDay: 150,
    extraKmPrice: 0.20,
    securityDeposit: 500,
    cleaningFee: 25,
    minDays: 2,
    maxDays: 30,
    bookingType: 'REQUEST_TO_BOOK',
    cancellationPolicy: 'MODERATE',
    status: 'ACTIVE',
    isDemoVehicle: true,
    description: 'Consumo súper bajo y tamaño perfecto para aparcar en cualquier rincón de Lanzarote sin llamar la atención. Asientos giratorios, cama desplegable sobre estructura de aluminio ultraligera, cocina de cartucho portátil para cocinar frente al mar en Famara y ducha exterior.',
    rules: 'No conducir bajo los efectos del alcohol. Devolver limpia y sin arena.',
    owner: {
      id: 'owner-demo-8',
      firstName: 'Jonay',
      lastName: 'Morales',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
      verification: 'VERIFIED',
      phone: '+34 688 991 223',
      email: 'jonay.morales@canarias-campers.local',
    },
    photos: [
      { id: 'p8-1', url: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1200', orderIndex: 0 },
      { id: 'p8-2', url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200', orderIndex: 1 },
    ],
    features: [
      { id: 'f8-1', name: 'Bajo consumo 6.9L' },
      { id: 'f8-2', name: 'Cama 125x195' },
      { id: 'f8-3', name: 'Asientos giratorios' },
      { id: 'f8-4', name: 'Cocina portátil exterior' },
      { id: 'f8-5', name: 'Ducha 12V' },
    ],
    reviews: [
      { id: 'r8-1', rating: 5, comment: 'Una pasada de furgoneta, facilísima de conducir y Jonay nos explicó todo al detalle.', author: { firstName: 'Lucía', avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200' } },
    ],
  },
  {
    id: 'demo-lp-9',
    slug: 'peugeot-boxer-wild-camp-l2h2-la-palma',
    title: 'Peugeot Boxer Wild Camp L2H2 La Isla Bonita',
    brand: 'Peugeot',
    model: 'Boxer Wild Camp 2.2 BlueHDi',
    vehicleType: 'CAMPER_GRAN_VOLUMEN',
    year: 2021,
    island: 'La Palma',
    municipality: 'Los Llanos de Aridane',
    addressApprox: 'Los Llanos / Puerto de Tazacorte',
    latitude: 28.6580,
    longitude: -17.9180,
    passengers: 2,
    beds: 2,
    doors: 4,
    transmission: 'MANUAL',
    fuelType: 'DIESEL',
    fuelConsumption: '8.1 L/100km',
    basePricePerDay: 75,
    includedKmPerDay: 150,
    extraKmPrice: 0.20,
    securityDeposit: 500,
    cleaningFee: 30,
    minDays: 2,
    maxDays: 30,
    bookingType: 'REQUEST_TO_BOOK',
    cancellationPolicy: 'MODERATE',
    status: 'ACTIVE',
    isDemoVehicle: true,
    description: 'Preparada específicamente para las carreteras empinadas de La Palma con motor potente de 140CV. Ducha interior, WC químico portátil, cocina con fregadero grande de acero inoxidable y depósito de agua de 100L para 4 días de autonomía total.',
    rules: 'No tirar toallitas ni residuos en el WC químico. Respetar la naturaleza de la isla.',
    owner: {
      id: 'owner-demo-9',
      firstName: 'Airam',
      lastName: 'Darias',
      avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400',
      verification: 'VERIFIED',
      phone: '+34 677 334 556',
      email: 'airam.darias@canarias-campers.local',
    },
    photos: [
      { id: 'p9-1', url: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=1200', orderIndex: 0 },
      { id: 'p9-2', url: 'https://images.unsplash.com/photo-1506015391300-4802dc74de2e?w=1200', orderIndex: 1 },
    ],
    features: [
      { id: 'f9-1', name: 'Motor 140CV potente' },
      { id: 'f9-2', name: 'Depósito agua 100L' },
      { id: 'f9-3', name: 'Ducha interior' },
      { id: 'f9-4', name: 'Placa solar 200W' },
      { id: 'f9-5', name: 'Calefacción Webasto' },
    ],
    reviews: [
      { id: 'r9-1', rating: 5, comment: 'La furgoneta sube las cuestas de La Palma sin despeinarse. Inolvidable viaje por los volcanes.', author: { firstName: 'Mario', avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200' } },
    ],
  },
  {
    id: 'demo-lg-10',
    slug: 'jeep-wrangler-unlimited-4x4-camper-la-gomera',
    title: 'Jeep Wrangler Unlimited 4x4 Camper Overland Edition',
    brand: 'Jeep',
    model: 'Wrangler Unlimited Rubicon',
    vehicleType: '4X4_CAMPERIZADO',
    year: 2023,
    island: 'La Gomera',
    municipality: 'San Sebastián de La Gomera',
    addressApprox: 'Cerca del Puerto de San Sebastián (Ferry Fred Olsen)',
    latitude: 28.0910,
    longitude: -17.1130,
    passengers: 4,
    beds: 2,
    doors: 4,
    transmission: 'AUTOMATIC',
    fuelType: 'GASOLINE',
    fuelConsumption: '9.5 L/100km',
    basePricePerDay: 115,
    includedKmPerDay: 150,
    extraKmPrice: 0.35,
    securityDeposit: 800,
    cleaningFee: 40,
    minDays: 2,
    maxDays: 30,
    bookingType: 'REQUEST_TO_BOOK',
    cancellationPolicy: 'MODERATE',
    status: 'ACTIVE',
    isDemoVehicle: true,
    description: 'El mítico 4x4 americano adaptado con tienda de techo de apertura rápida y toldo de 270 grados tipo murciélago. Perfecto para desembarcar del ferry en La Gomera y recorrer el bosque milenario de Garajonay con total libertad y estilo.',
    rules: 'Uso responsable del 4x4. No hacer trompos ni conducción temeraria. Prohibido fumar.',
    owner: {
      id: 'owner-demo-10',
      firstName: 'Cathaysa',
      lastName: 'Melián',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
      verification: 'VERIFIED',
      phone: '+34 699 001 122',
      email: 'cathaysa.melian@canarias-campers.local',
    },
    photos: [
      { id: 'p10-1', url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200', orderIndex: 0 },
      { id: 'p10-2', url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200', orderIndex: 1 },
    ],
    features: [
      { id: 'f10-1', name: 'Tracción Rubicon 4x4' },
      { id: 'f10-2', name: 'Toldo 270 grados' },
      { id: 'f10-3', name: 'Tienda de techo' },
      { id: 'f10-4', name: 'Nevera Dometic' },
    ],
    reviews: [
      { id: 'r10-1', rating: 5, comment: 'Un Jeep impresionante. Cathaysa nos esperó en la misma salida del barco. De 10.', author: { firstName: 'Néstor', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200' } },
    ],
  },
];
