'use client';
import { useEffect, useState } from 'react';
import Navbar from '@/components/Navbar';

export default function OwnerStatsPage() {
  const [data, setData] = useState<any>(null);
  useEffect(() => { fetch('/api/owner/analytics').then((response) => response.json()).then(setData); }, []);
  const stats = data?.stats;
  return <div className="min-h-screen bg-[#F7F6F2] text-[#13322E]"><Navbar /><main className="mx-auto max-w-6xl px-4 py-10"><span className="text-[11px] font-black uppercase tracking-[.25em] text-[#16B8AA]">Rendimiento real</span><h1 className="font-serif text-4xl font-bold">Estadísticas de tus anuncios</h1><p className="mt-2 text-sm text-[#6B726E]">Las visitas propias y de administradores no se contabilizan.</p>{!stats ? <p className="mt-10">Cargando…</p> : <><div className="my-8 grid gap-4 sm:grid-cols-5">{[['Apariciones', stats.impressions], ['Visitas', stats.views], ['Solicitudes', stats.requests], ['Confirmadas', stats.confirmed], ['Conversión', `${stats.conversion}%`]].map(([label, value]) => <div key={label} className="rounded-3xl border border-[#E9E1D2] bg-white p-6"><span className="text-xs font-bold uppercase text-[#6B726E]">{label}</span><strong className="mt-2 block font-serif text-4xl">{value}</strong></div>)}</div><section className="grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-[#E9E1D2] bg-white p-6"><h2 className="font-serif text-2xl font-bold">Por anuncio</h2>{stats.perVehicle.map((vehicle: any) => <div key={vehicle.id} className="mt-4 border-t border-[#E9E1D2] pt-4"><strong>{vehicle.title}</strong><p className="text-sm text-[#6B726E]">{vehicle.impressions} apariciones · {vehicle.views} visitas · {vehicle.requests} solicitudes · {vehicle.conversion}% conversión</p></div>)}</div><div className="rounded-3xl border border-[#E9E1D2] bg-white p-6"><h2 className="font-serif text-2xl font-bold">Procedencia de visitas</h2>{stats.countries.length ? stats.countries.map(([country, total]: [string, number]) => <div key={country} className="mt-4 flex justify-between border-t border-[#E9E1D2] pt-4"><span>{country}</span><strong>{total}</strong></div>) : <p className="mt-4 text-sm text-[#6B726E]">Todavía no hay datos de procedencia.</p>}</div></section></>}</main></div>;
}
