import type { Metadata } from 'next';
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
  title: 'Política de Cookies | vaneando.',
  description: 'Información sobre el uso de cookies y almacenamiento local en la plataforma Vaneando.',
  robots: {
    index: false,
    follow: true,
  },
};

export default function CookiesPage() {
  return <div className="min-h-screen bg-[#F7F6F2] text-[#13322E]"><Navbar /><main className="mx-auto max-w-4xl px-4 py-12"><article className="rounded-3xl border border-[#E9E1D2] bg-white p-8 shadow-sm sm:p-12"><div className="mb-8 border-b border-[#E9E1D2] pb-7"><span className="text-[11px] font-black uppercase tracking-[.25em] text-[#16B8AA]">Control de tu experiencia</span><h1 className="mt-2 font-serif text-4xl font-bold">Política de cookies</h1><p className="mt-3 text-sm leading-relaxed text-[#6B726E]">Última actualización: 11 de agosto de 2026.</p></div><div className="space-y-7 text-sm leading-7 text-[#52605B]"><section><h2 className="mb-2 font-serif text-xl font-bold">1. Qué son las cookies</h2><p>Son pequeños archivos que se guardan en tu dispositivo para mantener una sesión, recordar preferencias y entender cómo se utiliza la plataforma. Tecnologías equivalentes, como almacenamiento local, reciben el mismo tratamiento en esta política.</p></section><section><h2 className="mb-2 font-serif text-xl font-bold">2. Cookies necesarias</h2><p>Son imprescindibles para iniciar sesión, mantener tu rol de viajero o propietario, proteger formularios, conservar una reserva y recordar tus preferencias de cookies. No se utilizan para publicidad personalizada y no pueden desactivarse sin perder funciones esenciales.</p></section><section><h2 className="mb-2 font-serif text-xl font-bold">3. Cookies de preferencias</h2><p>Permiten recordar idioma, avisos ya vistos y opciones de interfaz. Solo se activan cuando son necesarias para ofrecer la preferencia que has solicitado.</p></section><section><h2 className="mb-2 font-serif text-xl font-bold">4. Medición y servicios externos</h2><p>Podremos incorporar medición agregada o servicios de terceros únicamente con la base legal y el consentimiento que corresponda. Los proveedores de pago, mapas, correo o seguridad pueden establecer sus propias cookies al prestar una función solicitada. Consulta sus políticas antes de utilizarlos.</p></section><section><h2 className="mb-2 font-serif text-xl font-bold">5. Cómo gestionar tus preferencias</h2><p>Puedes aceptar o rechazar las cookies no necesarias desde el aviso de privacidad de Vaneando y borrar las cookies desde la configuración de tu navegador. Bloquear las necesarias puede impedir el acceso, el pago o la gestión de reservas.</p></section><section><h2 className="mb-2 font-serif text-xl font-bold">6. Cambios y contacto</h2><p>Actualizaremos esta página si incorporamos nuevas tecnologías o cambia la normativa. Para dudas, escribe a <a className="font-bold text-[#0F766E] underline" href="mailto:contacto@vaneando.com">contacto@vaneando.com</a>.</p></section></div></article></main></div>;
}
