'use client';
import { KeyRound, Lock, ShieldCheck } from 'lucide-react';
import { useState } from 'react';

export default function AdminLogin() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function login(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(''); const response = await fetch('/api/auth', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'login', email, password }) }); const data = await response.json(); if (!response.ok) setError(data.error || 'No se pudo iniciar sesión'); else if (data.user?.role !== 'ADMIN') { await fetch('/api/auth', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'logout' }) }); setError('Esta cuenta no tiene permisos de administrador. Añádela a ADMIN_EMAILS.'); } else window.location.reload(); setLoading(false); }
  return <main className="mx-auto flex min-h-[70vh] max-w-md items-center px-4 py-12"><form onSubmit={login} className="w-full rounded-[32px] border border-[#E9E1D2] bg-white p-8 shadow-2xl"><div className="mb-6 flex h-14 w-14 items-center justify-center rounded-2xl bg-[#13322E] text-white"><ShieldCheck className="h-7 w-7 text-[#16B8AA]" /></div><span className="text-[10px] font-black uppercase tracking-[.25em] text-[#16B8AA]">Acceso restringido</span><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#13322E]">Administración de vaneando.</h1><p className="mt-2 text-sm text-[#6B726E]">Inicia sesión con uno de los correos autorizados en `ADMIN_EMAILS`.</p>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{error}</p>}<div className="mt-6 space-y-4"><label className="block text-xs font-black uppercase tracking-wider text-[#6B726E]">Correo administrativo<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1 w-full rounded-xl border border-[#E9E1D2] p-3 text-sm normal-case" /></label><label className="block text-xs font-black uppercase tracking-wider text-[#6B726E]">Contraseña<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-1 w-full rounded-xl border border-[#E9E1D2] p-3 text-sm normal-case" /></label><button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-full bg-[#13322E] py-4 text-xs font-bold uppercase tracking-wider text-white"><KeyRound className="h-4 w-4" />{loading ? 'Comprobando…' : 'Entrar al panel'}</button></div><p className="mt-5 flex items-center gap-2 text-[11px] text-[#6B726E]"><Lock className="h-3.5 w-3.5" />La ruta es siempre vaneando.com/admin</p></form></main>;
}
