'use client';
import { useEffect, useState } from 'react';

export default function OwnerAvailabilityCalendar({ vehicles }: { vehicles: any[] }) {
  const [vehicleId, setVehicleId] = useState(vehicles[0]?.id || ''); const [blocks, setBlocks] = useState<any[]>([]); const [startDate, setStartDate] = useState(''); const [endDate, setEndDate] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { if (vehicleId) fetch(`/api/vehicles/${vehicleId}/availability`).then((r) => r.json()).then((d) => setBlocks(d.blocks || [])); }, [vehicleId]);
  async function addBlock(e: React.FormEvent) { e.preventDefault(); const r = await fetch(`/api/vehicles/${vehicleId}/availability`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ startDate, endDate, reason: 'OWNER_BLOCK' }) }); const d = await r.json(); if (r.ok) { setBlocks([...blocks, d.block]); setMessage('Fechas bloqueadas'); } else setMessage(d.error); }
  return <section className="mb-12 rounded-3xl border border-[#E9E1D2] bg-white p-6"><h2 className="font-serif text-2xl font-bold mb-4">Disponibilidad de la flota</h2><div className="flex flex-wrap gap-3 mb-4"><select value={vehicleId} onChange={(e) => setVehicleId(e.target.value)} className="rounded-xl border p-3 text-sm">{vehicles.map((v) => <option key={v.id} value={v.id}>{v.title}</option>)}</select><form onSubmit={addBlock} className="flex flex-wrap gap-2"><input required type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="rounded-xl border p-3 text-sm" /><input required type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} className="rounded-xl border p-3 text-sm" /><button className="rounded-full bg-[#13322E] px-4 py-3 text-xs font-bold text-white">Bloquear fechas</button></form></div>{message && <p className="mb-3 text-xs font-bold text-amber-700">{message}</p>}<div className="space-y-2">{blocks.length === 0 ? <p className="text-sm text-[#6B726E]">No hay bloqueos para esta camper.</p> : blocks.map((block) => <div key={block.id} className="rounded-xl bg-slate-50 px-4 py-3 text-sm">{new Date(block.startDate).toLocaleDateString()} – {new Date(block.endDate).toLocaleDateString()} <span className="text-xs text-slate-500">({block.reason})</span></div>)}</div></section>;
}
