'use client';

const green = '#13322E';
const teal = '#16B8AA';
const border = '#E9E1D2';

function Email({ title, intro, children, button }: { title: string; intro: string; children: React.ReactNode; button: string }) {
  return <article className="overflow-hidden rounded-3xl border bg-white shadow-sm" style={{ borderColor: border }}><header className="px-6 py-8 text-center text-white" style={{ background: green }}><div className="font-serif text-3xl font-bold">vaneando<span style={{ color: teal }}>.com</span></div><div className="mt-2 text-[10px] font-bold tracking-[.25em]" style={{ color: teal }}>CANARIAS SOBRE RUEDAS</div></header><div className="space-y-5 p-6"><h2 className="font-serif text-2xl font-bold" style={{ color: green }}>{title}</h2><p className="text-sm leading-6 text-slate-600">{intro}</p><div className="rounded-2xl border p-4 text-sm leading-7" style={{ borderColor: border, background: '#FAF7F0' }}>{children}</div><button className="rounded-full px-5 py-3 text-xs font-black text-white" style={{ background: teal }}>{button}</button></div><footer className="border-t px-6 py-4 text-center text-xs text-slate-500" style={{ borderColor: border }}>vaneando.com · Datos de demostración</footer></article>;
}

function Payment({ state, children, button }: { state: string; children: React.ReactNode; button: string }) { return <article className="rounded-3xl border bg-white p-6 shadow-sm" style={{ borderColor: border }}><h2 className="font-serif text-2xl font-bold" style={{ color: green }}>{state}</h2><p className="mt-2 text-sm text-slate-500">Camper Chancleta · 10/09/2026 - 15/09/2026</p>{children}<button className="mt-6 w-full rounded-full px-5 py-3 text-xs font-black text-white" style={{ background: teal }}>{button}</button><p className="mt-4 text-center text-xs text-slate-500">🔒 Pago seguro procesado por Stripe</p></article>; }

export default function PreviewPage() {
  return <main className="min-h-screen bg-[#F7F6F2] px-4 py-10 text-[#13322E] sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.25em] text-[#16B8AA]">Entorno de demostración</p><h1 className="mt-2 font-serif text-4xl font-bold">Previsualizaciones de Vaneando</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Emails y pantallas de pago con datos ficticios. Esta página no crea reservas, no procesa tarjetas y no envía correos.</p><h2 className="mb-5 mt-10 font-serif text-3xl font-bold">Emails</h2><section className="grid gap-6 lg:grid-cols-3"><Email title="¡Nueva solicitud de reserva! 🚐" intro="Hola Alejandro, un viajero quiere alquilar tu camper." button="Gestionar reserva"><b>Viajero:</b> Nombre de prueba<br/><b>Vehículo:</b> Camper Chancleta<br/><b>Fechas:</b> 10/09/2026 - 15/09/2026<br/><b>Código:</b> NC-AB12CD34</Email><Email title="¡Reserva instantánea recibida!" intro="Un viajero ha reservado tu camper. La reserva queda pendiente de completar el proceso." button="Ver reserva"><b>Vehículo:</b> Camper Chancleta<br/><b>Estado:</b> Reserva instantánea<br/><b>Código:</b> NC-AB12CD34</Email><Email title="¡Pago confirmado y factura! 🎉" intro="Tu reserva para disfrutar de Camper Chancleta está confirmada." button="Ver factura"><b>Alquiler: 450,00 €</b><br/>Gestión: 43,65 €<br/>IGIC: 34,57 €<br/><strong className="text-lg" style={{ color: teal }}>Total: 493,65 €</strong></Email></section><h2 className="mb-5 mt-12 font-serif text-3xl font-bold">Stripe y estados de pago</h2><section className="grid gap-6 lg:grid-cols-3"><Payment state="Formulario de pago" button="Pagar 493,65 €"><label className="mt-6 block text-xs font-bold">Número de tarjeta<input className="mt-2 w-full rounded-xl border p-3" style={{ borderColor: border }} placeholder="4242 4242 4242 4242" /></label><div className="mt-4 grid grid-cols-2 gap-3"><input className="rounded-xl border p-3" style={{ borderColor: border }} placeholder="MM/AA"/><input className="rounded-xl border p-3" style={{ borderColor: border }} placeholder="CVC"/></div></Payment><Payment state="Pago pendiente" button="Continuar pago"><div className="my-12 text-center"><div className="text-5xl">⏳</div><p className="mt-4 text-sm text-slate-600">El contrato está firmado. Completa el pago para confirmar la reserva.</p></div></Payment><Payment state="Pago confirmado" button="Ver reserva"><div className="my-12 text-center"><div className="text-5xl text-[#16B8AA]">✓</div><p className="mt-4 text-sm text-slate-600">Tu reserva está confirmada. Hemos enviado la factura por email.</p></div></Payment></section></div></main>;
}
